"""Initial Migration

Revision ID: 15b4042115cd
Revises: 3b7cf1d6d132
Create Date: 2019-09-25 12:30:02.814488

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15b4042115cd'
down_revision = '3b7cf1d6d132'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('category', sa.String(length=255), nullable=False))
    op.add_column('users', sa.Column('category', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_users_category'), 'users', ['category'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_category'), table_name='users')
    op.drop_column('users', 'category')
    op.drop_column('blogs', 'category')
    # ### end Alembic commands ###
