"""Initial Migration

Revision ID: 599a9044c813
Revises: ca588f4f18cb
Create Date: 2019-09-30 11:40:28.972660

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '599a9044c813'
down_revision = 'ca588f4f18cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscribers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subscribers')
    # ### end Alembic commands ###
