"""Initial Migration

Revision ID: ca588f4f18cb
Revises: 72e882174e9b
Create Date: 2019-09-30 09:10:29.533282

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ca588f4f18cb'
down_revision = '72e882174e9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('date_posted', sa.DateTime(), nullable=True))
    op.drop_column('users', 'date_posted')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('date_posted', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('blogs', 'date_posted')
    # ### end Alembic commands ###
